# Generated by Django 2.0.4 on 2018-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnee_pharmacie',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
